### ISSUE TITLE
Travis Build Failure with multiple parser tests

### ISSUE THREAD

**Issue by HugoKooijman** [ProgrammingLife2016/PL3-2016#34]
Whereas Eclipse does not give me any more errors, when calling the parse() function multiple times, Travis still does. It throws DbExceptions, where primary keys are violated. This was solved for local test runs with separating the files into different directories, but this doesn't work on Travis.

**Comment by DvdBerg** [comment]
@HugoKooijman, is this still an issue? If so, could you try to resolve it? Otherwise, please close it.

**Comment by DvdBerg** [comment]
As mentioned in the WhatsApp group, this issue has already been solved.
