### ISSUE TITLE
Change ribbon lines into curves

### ISSUE THREAD

**Issue by DvdBerg** [ProgrammingLife2016/PL3-2016#57]
Change the straight lines from the ribbon view into curves, so that very long lines will not cross other lines but travel above them. The new curved line should go up/down at the location they split off the main "branch", and "merge" back in the opposite way (in between, the ribbon should be a straight line).

**Comment by RobKapel** [comment]
Still on a seperate branch, but a basic version is implemented in the GUI/CurvedRibbons branch.

**Comment by DvdBerg** [comment]
As discussed, we don't know for sure yet how this will be integrated into the final result. Since it is working and finished, I will close this issue for now.
