### ISSUE TITLE
Ribbon - graph link

### ISSUE THREAD

**Issue by DvdBerg** [ProgrammingLife2016/PL3-2016#80]
Implement the carry-over of coordinates between the ribbon and low level graph tabs. This means that when switching tabs, the position in the graph should remain the same. This is a first step to the integration of the low level graph and the ribbon.

**Comment by DvdBerg** [comment]
@BjornHo will cooperate on this issue.

**Comment by RobKapel** [comment]
This is now implemented and merged into the master branch.
